# Generated by Django 4.2.30 on 2026-07-15 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('learning', 'Learning & Scholarships'), ('volunteering', 'Volunteering'), ('working', 'Working & Internships'), ('making_change', 'Making a Change'), ('competing', 'Competing')], max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_worldwide', models.BooleanField(db_index=True, default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('is_onsite', models.BooleanField(default=False)),
                ('deadline', models.DateField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='opportunities.category')),
                ('destination_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_opportunities', to='opportunities.country')),
                ('eligible_home_countries', models.ManyToManyField(blank=True, related_name='eligible_opportunities', to='opportunities.country')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='opportuniti_name_b25826_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['iso_code'], name='opportuniti_iso_cod_775541_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['deadline', 'is_active'], name='opportuniti_deadlin_e7b8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['min_age', 'max_age'], name='opportuniti_min_age_3e4fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['is_worldwide', 'is_online'], name='opportuniti_is_worl_0235cb_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['-created_at'], name='opportuniti_created_1b69e8_idx'),
        ),
    ]
