# Generated by Django 4.2.30 on 2026-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
