# Generated by Django 4.2.30 on 2026-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunity_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='application_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
