# Generated by Django 4.2.30 on 2026-07-15 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(help_text='Raw payload received from n8n')),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('rejected', 'Rejected')], max_length=20)),
                ('errors', models.JSONField(blank=True, help_text='Serializer validation errors if rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_logs', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='ingestion_i_status_cc351f_idx'), models.Index(fields=['created_at'], name='ingestion_i_created_feefca_idx')],
            },
        ),
    ]
